filters:
  comments: true
plugins:
  "@textlint/markdown":
    extensions: .md
rules:
  preset-japanese:
    sentence-length:
      max: 110
  no-todo: true # - [ ] や todo があるとエラーになる
  spellcheck-tech-word: true
