# https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml

# Site Settings
locale: "ja-JP"
title: "I am Haruka."
title_separator: "@"
subtitle: "Version 1.0" # site tagline that appears below site title in masthead
name: &name "Haruka"
description: &description "はるかのエンジニア活動とかまとめていけたらなってサイト"
url: "https://hulk510.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: "" # the subpath of your site, e.g. "/blog"
# repository: # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
# teaser: # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# logo: # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
# masthead_title: # overrides the website title displayed in the masthead, use " " for no title
og_image: /assets/images/avatar.png

# Collections
collections:
  resume:
    output: true
    permalink: /:collection/:path
  portfolio:
    output: true
    permalink: /:collection/:path

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dirt" #"air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
  - jekyll-include-cache

include: ["_pages"]

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - README.md

# ビルド時エラー出るため付与してる
github: [metadata]

# パンクズ
breadcrumbs: true

# Site Author
author:
  name: *name
  avatar: "/assets/images/avatar.png"
  bio: "Engineer"
  location: "Osaka, Japan"
  email: "dorian.51069@gmail.com"
  links:
    - label: "Zenn"
      icon: "fas fa-fw fa-link"
      url: "https://zenn.dev/hulk510"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/kcash510"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hulk510"
    - label: "note"
      icon: "far fa-fw fa-sticky-note"
      url: "https://note.com/hulk510"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/kcash510"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hulk510"

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      toc: true
      permalink: /blog/:title/
      share: true
  # _resume
  - scope:
      path: ""
      type: resume
    values:
      layout: single
      author_profile: true
      toc: true
      toc_sticky: true
      classes: wide
      sidebar:
        nav: "tree"
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-9MZPPZZL8C"
    anonymize_ip: false # default

atom_feed:
  hide: true
